Repository google/keytransparency, pull requests merged in 2019-03, with the labels that each got.

#1224 Make the reduceFn associative
  core/mutator/entry/entry.go
  core/mutator/entry/entry_test.go
  core/mutator/entry/mutator.go
  core/mutator/mutator.go
  core/sequencer/mapper/fns.go
  core/sequencer/runner/native.go
  core/sequencer/runner/native_test.go
Labels: cla: yes

#1226 Reduce batch_size and timeouts
  core/integration/client_tests.go
Labels: cla: yes

#1227 Fix reversed arguments
  core/mutator/entry/mutator.go
Labels: cla: yes

#1229 Simplify MapLogItems
  core/sequencer/runner/native.go
  core/sequencer/server.go
Labels: cla: yes

#1230 Fix invalid http.body mapping for KeyTransparencyFrontend.QueueKeyUpdate
  core/api/v1/frontend.proto
Labels: cla: yes

#1231 Emit errors during the mapping phase
  core/mutator/entry/mutator.go
  core/mutator/mutator.go
  core/sequencer/runner/native.go
  core/sequencer/server.go
Labels: cla: yes, cleanup

#1228 Fix: Allow multiple updates to the same user in the same batch
  core/sequencer/server.go
  core/sequencer/server_test.go
Labels: bug, cla: yes

#1235 Fix error metric
  core/sequencer/server.go
Labels: cla: yes

#1236 Add log message
  core/sequencer/sequencer.go
Labels: cla: yes

#1234 Complete ApplyRevisions MR pipeline
  core/client/client.go
  core/mutator/mutator.go
  core/sequencer/runner/native.go
  core/sequencer/server.go
Labels: cla: yes

#1239 go generate ./...
  core/api/monitor/v1/monitor_go_proto/monitor.pb.gw.go
  core/api/v1/keytransparency_go_proto/admin.pb.gw.go
  core/api/v1/keytransparency_go_proto/frontend.pb.go
  core/api/v1/keytransparency_go_proto/frontend.pb.gw.go
  core/api/v1/keytransparency_go_proto/keytransparency.pb.gw.go
Labels: cla: yes

#1232 Read LogMessages in a MapFn
  core/mutator/mutator.go
  core/sequencer/mapper/fns.go
  core/sequencer/runner/native.go
  core/sequencer/server.go
  core/sequencer/server_test.go
Labels: cla: yes

#1238 Add error codes to mutation errors
  core/mutator/mutator.go
Labels: cla: yes

#1240 Remove references to tinkpb.Keyset
  cmd/keytransparency-client/cmd/post.go
  core/api/type/type.proto
  core/api/type/type_go_proto/keymaster.pb.go
  core/api/type/type_go_proto/type.pb.go
  core/api/v1/keytransparency.proto
  core/api/v1/keytransparency_go_proto/keytransparency.pb.go
  core/client/batch_client.go
  core/client/client.go
  core/client/hammer/hammer.go
  core/client/user.go
  core/frontend/frontend.go
  core/integration/client_tests.go
  core/integration/monitor_tests.go
  core/mutator/entry/mutation.go
  core/mutator/entry/mutation_test.go
  core/mutator/entry/mutator.go
  core/mutator/entry/mutator_test.go
  core/sequencer/server_test.go
  docs/api.md
Labels: cla: yes

#1242 Transition off of deprecated gAPI.New
  cmd/keytransparency-server/main.go
  impl/authentication/google.go
  impl/authentication/google_test.go
Labels: bug, cla: yes

#1241 Add metrics for each stage of the sequencing pipeline
  core/sequencer/runner/native.go
  core/sequencer/runner/native_test.go
  core/sequencer/server.go
  core/sequencer/server_test.go
Labels: cla: yes

#1243 Fix lint comment
  core/sequencer/runner/native.go
Labels: cla: yes

#1246 Remove unused keyset storage
  impl/sql/keysets/keysets.go
  impl/sql/keysets/keysets_test.go
Labels: cla: yes

#1245 Short term fix for large cardinality
  core/sequencer/server.go
Labels: cla: yes

#1247 Fixes for use of deprecated fields in SignedLogRoot.
  core/keyserver/keyserver.go
  core/keyserver/keyserver_test.go
  core/keyserver/revisions.go
Labels: cla: yes

#1248 Add Canonical Err Codes
  core/mutator/entry/mutator.go
  core/sequencer/runner/native.go
Labels: cla: yes

#1237 Add metric for unapplied log entries
  cmd/keytransparency-sequencer/main.go
  core/sequencer/sequencer_api.proto
  core/sequencer/sequencer_go_proto/sequencer_api.pb.go
  core/sequencer/server.go
Labels: cla: yes

#1249 Emit index for empty map leaf
  core/mutator/entry/entry.go
  core/mutator/entry/entry_test.go
Labels: cla: yes

#1252 Add latency metrics to ApplyRevisions in Sequencer
  core/sequencer/server.go
Labels: cla: yes

#1253 Remove trailing whitespace in sequencer_api.proto
  core/sequencer/sequencer_api.proto
Labels: cla: yes

#1250 {List,Create,Change}InputLogs Admin APIs
  core/adminserver/admin_server.go
  core/adminserver/admin_server_test.go
  core/api/gen.go
  core/api/monitor/v1/monitor_go_proto/monitor.pb.go
  core/api/v1/admin.proto
  core/api/v1/keytransparency_go_proto/admin.pb.go
  core/api/v1/keytransparency_go_proto/admin.pb.gw.go
  core/api/v1/keytransparency_go_proto/frontend.pb.go
  core/api/v1/keytransparency_go_proto/keytransparency.pb.go
  core/sequencer/sequencer_go_proto/sequencer_api.pb.go
  docs/api.md
  impl/sql/mutationstorage/queue.go
  impl/sql/mutationstorage/queue_test.go
Labels: cla: yes
