Repository google/keytransparency, pull requests merged in 2019-07, with the labels that each got.

#1303 Configurable maximum queue depth for metric reporting.
  cmd/keytransparency-sequencer/main.go
  core/sequencer/sequencer_api.proto
  core/sequencer/sequencer_go_proto/sequencer_api.pb.go
  core/sequencer/server.go
Labels: cla: yes

#1304 Use new TrillianMapWrite API
  cmd/keytransparency-sequencer/main.go
  core/sequencer/server.go
  core/sequencer/server_test.go
  core/sequencer/trillian_client.go
  go.mod
  go.sum
  impl/integration/env.go
Labels: cla: yes

#1305 go mod tidy
  go.mod
  go.sum
Labels: cla: yes

#1308 Fix proto copying in server_test.
  core/sequencer/server.go
  core/sequencer/server_test.go
Labels: cla: yes

#1309 Fix proto copying in revisions and paginator tests.
  core/keyserver/paginator_test.go
  core/keyserver/revisions_test.go
Labels: cla: yes

#1306 go generate ./...
  core/api/monitor/v1/monitor_go_proto/monitor.pb.gw.go
  core/api/v1/keytransparency_go_proto/admin.pb.gw.go
  core/api/v1/keytransparency_go_proto/frontend.pb.gw.go
  core/api/v1/keytransparency_go_proto/keytransparency.pb.gw.go
Labels: cla: yes

#1312 Move the KT verifier to its own package
  core/client/client.go
  core/client/client_test.go
  core/client/verifier/verifier.go
  core/client/verifier/verifier_test.go
Labels: cla: yes

#1310 Track map revision inside mutation
  core/client/batch_client.go
  core/client/batch_get_and_verify.go
  core/client/client.go
  core/client/get_and_verify.go
  core/client/gobindclient/client.go
  core/mutator/entry/mutation.go
  core/mutator/entry/mutation_test.go
Labels: bug, cla: yes

#1315 New test vector transcript format
  core/api/gen.go
  core/client/verifier/verifier_test.go
  core/crypto/vrf/p256/p256_test.go
  core/integration/alltests.go
  core/integration/client_tests.go
  core/integration/monitor_tests.go
  core/testdata/TestBatchCreate.json
  core/testdata/TestBatchGetUser.json
  core/testdata/TestBatchListUserRevisions.json
  core/testdata/TestBatchUpdate.json
  core/testdata/TestEmptyGetAndUpdate.json
  core/testdata/TestListHistory.json
  core/testdata/TestMonitor.json
  core/testdata/batch_get_user.json
  core/testdata/batch_list_user_revisions.json
  core/testdata/directory_batch_get_user.json
  core/testdata/directory_batch_list_user_revisions.json
  core/testdata/directory_get_and_update.json
  core/testdata/get_and_update.json
  core/testdata/io.go
  core/testdata/transcript_go_proto/gen.go
  core/testdata/transcript_go_proto/transcript.pb.go
  core/testdata/transcript_go_proto/transcript.proto
  core/testdata/types.go
  impl/integration/main_test.go
Labels: cla: yes

#1319 Remove unnessesary func()
  impl/integration/main_test.go
Labels: cla: yes

#1314 Pass along err message
  core/keyserver/keyserver.go
Labels: cla: yes

#1316 Encapsulate Client Verifier State in test vectors
  core/api/v1/keytransparency.proto
  core/api/v1/keytransparency_go_proto/keytransparency.pb.go
  core/client/verifier/verifier_test.go
  core/integration/client_tests.go
  core/testdata/TestBatchCreate.json
  core/testdata/TestBatchGetUser.json
  core/testdata/TestBatchListUserRevisions.json
  core/testdata/TestBatchUpdate.json
  core/testdata/TestEmptyGetAndUpdate.json
  core/testdata/TestListHistory.json
  core/testdata/TestMonitor.json
  core/testdata/transcript_go_proto/transcript.pb.go
  core/testdata/transcript_go_proto/transcript.proto
  docs/api.md
Labels: cla: yes

#1321 Remove trailing whitespace
  core/testdata/transcript_go_proto/transcript.proto
Labels: cla: yes

#1320 Remove VerifySignedMapRoot from VerifierInterface
  core/client/client.go
  core/client/mutations.go
  core/monitor/monitor.go
Labels: cla: yes

#1307 Make check-set mutation semantics optional
  core/mutator/entry/mutation.go
  core/mutator/entry/mutator.go
  core/mutator/entry/mutator_test.go
Labels: cla: yes

#1318 Split VerifyRevision into Verify{LogRoot,MapRevision
  core/client/batch_get_and_verify.go
  core/client/client.go
  core/client/client_test.go
  core/client/get_and_verify.go
  core/client/verifier/verifier.go
  core/client/verifier/verifier_test.go
  core/integration/client_tests.go
  core/monitor/monitor.go
Labels: cla: yes, cleanup

#1322 Pair verifier functions
  core/client/client.go
  core/client/client_test.go
  core/client/get_and_verify.go
  core/client/verifier/pairs.go
  core/client/verifier/verifier_test.go
  core/integration/client_tests.go
Labels: cla: yes

#1323 Verify Revisions in StreamRevisions
  cmd/keytransparency-monitor/main.go
  core/client/get_and_verify.go
  core/client/mutations.go
  core/integration/monitor_tests.go
  core/monitor/monitor.go
  core/monitor/monitor_test.go
  core/monitor/verify.go
Labels: cla: yes

#1324 Remove unused logVerifier
  core/monitor/monitor.go
Labels: cla: yes

#1317 Extract log tracking into separate package
  core/client/batch_get_and_verify.go
  core/client/client.go
  core/client/client_test.go
  core/client/get_and_verify.go
  core/client/tracker/tracker.go
  core/client/tracker/tracker_test.go
  core/client/verifier/pairs.go
  core/client/verifier/verifier.go
  core/client/verifier/verifier_test.go
  core/integration/client_tests.go
  core/monitor/monitor.go
Labels: cla: yes

#1325 Cache go mod download
  cmd/keytransparency-monitor/Dockerfile
  cmd/keytransparency-sequencer/Dockerfile
  cmd/keytransparency-server/Dockerfile
Labels: cla: yes

#1201 Add docker-compose integration test
  .travis.yml
  docker-compose.yml
  scripts/integration.sh
Labels: cla: yes

#1327 Tracker Factory for dependency injection
  cmd/keytransparency-client/cmd/root.go
  core/client/client.go
  core/client/gobindclient/client.go
  core/client/hammer/hammer.go
  core/client/tracker/tracker.go
  core/client/verifier/verifier.go
  core/client/verifier/verifier_test.go
  core/integration/client_tests.go
  core/monitor/monitor.go
  impl/integration/env.go
Labels: cla: yes

#1191 Remove secrets from Docker Images
  README.md
  cmd/keytransparency-monitor/Dockerfile
  cmd/keytransparency-server/Dockerfile
  docker-compose.override.yml
  docker-compose.prod.yml
  docker-compose.yml
  scripts/gen_monitor_keys.sh
  scripts/gen_server_keys.sh
  scripts/prepare_server.sh
Labels: cla: yes, security
