Repository google/keytransparency, pull requests merged in 2019-02, with the labels that each got.

#1132 Refactor ApplyMutations into its own package
  core/sequencer/mapper/fns.go
  core/sequencer/runner/native.go
  core/sequencer/runner/native_test.go
  core/sequencer/server.go
  core/sequencer/server_test.go
Labels: for review

#1195 Don't timeout users entering OAuth info
  cmd/keytransparency-client/cmd/post.go
Labels: bug

#1199 Fix hang: run mastership tracker
  cmd/keytransparency-sequencer/main.go
Labels: bug

#1215 update travis.yml to xenial
  .travis.yml
Labels: cla: yes

#1223 Added keyset-file flag tp specify file path and name
  README.md
  cmd/keytransparency-client/cmd/hammer.go
  cmd/keytransparency-client/cmd/keys.go
  cmd/keytransparency-client/cmd/post.go
Labels: cla: yes

#1220 Move reduceFn to mutator definition
  core/client/client.go
  core/mutator/entry/mutator.go
  core/mutator/mutator.go
  core/sequencer/mapper/fns.go
  core/sequencer/runner/native.go
  core/sequencer/server.go
Labels: cla: yes
