Repository google/keytransparency, pull requests merged in 2019-08, with the labels that each got.

#1329 Include LogRootRequest in Request Protos
  core/api/v1/keytransparency.proto
  core/api/v1/keytransparency_go_proto/keytransparency.pb.go
  core/client/batch_get_and_verify.go
  core/client/client.go
  core/client/client_test.go
  core/client/get_and_verify.go
  core/client/verifier/pairs.go
  core/client/verifier/verifier_test.go
  core/integration/client_tests.go
  core/keyserver/keyserver.go
  core/keyserver/revisions.go
  core/sequencer/sequencer_api.proto
  core/testdata/TestBatchCreate.json
  core/testdata/TestBatchGetUser.json
  core/testdata/TestBatchListUserRevisions.json
  core/testdata/TestBatchUpdate.json
  core/testdata/TestEmptyGetAndUpdate.json
  core/testdata/TestListHistory.json
  core/testdata/TestMonitor.json
  core/testdata/transcript_go_proto/transcript.pb.go
  core/testdata/transcript_go_proto/transcript.proto
  docs/api.md
Labels: cla: yes

#1330 Turn on GOPROXY
  .travis.yml
  cmd/keytransparency-monitor/Dockerfile
  cmd/keytransparency-sequencer/Dockerfile
  cmd/keytransparency-server/Dockerfile
  go.mod
  go.sum
Labels: cla: yes

#1331 Use Travis Build Stages
  .travis.yml
Labels: cla: yes, dependent

#1328 Use constant time P256 implementation
  core/crypto/vrf/p256/p256.go
  core/crypto/vrf/p256/p256_test.go
Labels: cla: yes, dependent

#1338 Revert "Turn on GOPROXY"
  .travis.yml
  cmd/keytransparency-monitor/Dockerfile
  cmd/keytransparency-sequencer/Dockerfile
  cmd/keytransparency-server/Dockerfile
  go.mod
  go.sum
Labels: cla: yes

#1339 Improve integration script reliability
  scripts/integration.sh
Labels: cla: yes

#1334 Check for data races in travis
  .travis.yml
  core/client/batch_get_and_verify.go
  core/keyserver/keyserver.go
  go.mod
  go.sum
Labels: cla: yes

#1340 Deprecate unused RunBatch parameter
  core/integration/client_tests.go
  core/sequencer/sequencer_api.proto
  core/sequencer/sequencer_go_proto/sequencer_api.pb.go
Labels: cla: yes

#1341 integration: Factor out helper to run batch and publish
  core/integration/client_tests.go
  core/integration/monitor_tests.go
Labels: cla: yes

#1342 gotip mod tidy
  go.mod
  go.sum
Labels: cla: yes

#1343 Initialize mutations batch 0 with zero watermarks
  cmd/keytransparency-sequencer/main.go
  core/adminserver/admin_server.go
  core/adminserver/admin_server_test.go
  impl/integration/env.go
Labels: cla: yes

#1344 Read batch definitions from batch storage
  core/sequencer/server.go
  core/sequencer/server_test.go
Labels: bug, cla: yes

#1345 Batch storage integration tests
  core/integration/storagetest/batch.go
  impl/sql/mutationstorage/mutations.go
  impl/sql/mutationstorage/mutations_test.go
  impl/sql/mutationstorage/queue_test.go
Labels: cla: yes

#1347 Fix deployment script. Use gcr.io consistently
  deploy/kubernetes/db-deployment.yaml
  deploy/kubernetes/init-pod.yaml
  deploy/kubernetes/log-server-deployment.yaml
  deploy/kubernetes/log-signer-deployment.yaml
  deploy/kubernetes/map-server-deployment.yaml
  deploy/kubernetes/monitor-deployment.yaml
  deploy/kubernetes/prometheus-deployment.yaml
  deploy/kubernetes/sequencer-deployment.yaml
  deploy/kubernetes/server-deployment.yaml
  scripts/deploy.sh
Labels: cla: yes

#1348 Run directory detection independently
  cmd/keytransparency-sequencer/main.go
Labels: cla: yes

#1332 Fix deploy scripts
  scripts/deploy.sh
  scripts/gen_server_keys.sh
Labels: cla: yes, dependent

#1349 Use pair of edge revisions instead of listing all
  core/sequencer/sequencer_api.proto
  core/sequencer/sequencer_go_proto/sequencer_api.pb.go
  core/sequencer/server.go
  core/sequencer/server_test.go
Labels: cla: yes

#1335 Factor out defining revisions into an async job
  cmd/keytransparency-sequencer/main.go
  core/integration/client_tests.go
  core/sequencer/sequencer.go
  core/sequencer/sequencer_api.proto
  core/sequencer/sequencer_go_proto/sequencer_api.pb.go
  core/sequencer/server.go
  core/sequencer/server_test.go
Labels: cla: yes

#1351 Rename RunBatch to ApplyRevisions
  cmd/keytransparency-sequencer/main.go
  core/integration/client_tests.go
  core/sequencer/sequencer.go
  core/sequencer/sequencer_api.proto
  core/sequencer/sequencer_go_proto/sequencer_api.pb.go
  core/sequencer/server.go
Labels: cla: yes
